### PR TITLE
Added build script to generate artifacts

### PR DESCRIPTION
**Pull request by owaiskazi19**
### Description
- Added build script to generate artifacts
- Added artifacts and sources jar
- Handle git command issue while building the plugin with manifest

### Issues Resolved
Part of https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/165

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by owaiskazi19** [comment]
Need review from @gaiksaya

**Review by dbwiddis — APPROVED** [review]
LGTM (pending removal of dupe file)

**Comment by gaiksaya** [comment]
Cross posting from build issue:

The I tried building this plugin. Just one issue, the plugin name does not match what is stated in the issue as well as repo name:

```
      plugins:
        - plugins/opensearch-flow-framework-2.12.0.0.zip
    version: 2.12.0.0
```
Please fix this. Thanks!

**Comment by joshpalis** [comment]
@owaiskazi19 perhaps its time to change the repo name since we've opted not to use `ai` in our plugin

**Comment by owaiskazi19** [comment]
> @owaiskazi19 perhaps its time to change the repo name since we've opted not to use `ai` in our plugin

https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/168

**Comment by owaiskazi19** [comment]
Let's hold this PR until #168 is completed.

**Review by gaiksaya — APPROVED** [review]

**Pull request merged**
