### PR TITLE
Eliminate Google Guava dependency

### LINKED ISSUE #328: [FEATURE] Eliminate all use of Google Guava
### Is your feature request related to a problem?

Google Guava is a monolithic "kitchen sink" dependency with [recent CVEs](https://www.cvedetails.com/vulnerability-list/vendor_id-1224/product_id-52274/Google-Guava.html) and a huge (2.9 MB) jar which has tons of utility classes we don't need.

Most of our use of it was for the former Google Collections project's `ImmutableList` and `ImmutableMap` made obsolete by Java 9's `List.of` and `Map.of`, that I've removed in #327.

### What solution would you like?

We still have one remaining use of it for (former Google Commons IO) code reading our mapping JSON files, 3 instances of:
```java
import com.google.common.io.Resources;

URL url = <class name>.class.getClassLoader().getResource(mapping);
return Resources.toString(url, StandardCharsets.UTF_8);
```

We should create a utility class to do this reading without using a large dependency. It's possible in pure Java by replacing `getResource()` with `getResourceAsStream()` and processing the resulting InputStream with one of many built-in ways (Scanner, BufferedReader, ByteArrayOutputStream).  

Here's some code I've hand-edited from an OpenSearch test class (`o.o.search.geo.GeoFilterIT.unZipData()`) that might work:
```java
import org.opensearch.common.io.Streams;

private static String readMappingJSON(String path) throws IOException {
    try (InputStream is = Streams.class.getResourceAsStream(path)) {
        if (is == null) {
            throw new FileNotFoundException("Resource [" + path + "] not found in classpath");
        }
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            Streams.copy(is, baos);
            return new String(baos.toByteArray(), StandardCharsets.UTF_8);
        }
    }
}
```

Although now that I see that `Streams` class I can see it has some other methods, like a `readAllLines()`.  `o.o.discovery.gce.GceMockUtils` has a `readJsonResponse` method that uses the `BufferedReader` approach, so you could do this:
```java
try (InputStream is = Streams.class.getResourceAsStream(path)) {
    if (is == null) {
        throw new FileNotFoundException("Resource [" + path + "] not found in classpath");
    }
    final StringBuilder sb = new StringBuilder();
    Streams.readAllLines(is, sb::append);
    return sb.toString();
}
```

### What alternatives have you considered?

Scanner, BufferedReader, other dependencies.

### PR DESCRIPTION
**Pull request by dbwiddis**
### Description

```diff
-    implementation "com.google.guava:guava:33.0.0-jre"
```

### Issues Resolved

Fixes #328

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by amitgalitz** [comment]
I see there is a good amount of failed tests in CI, was this occurring locally too?

**Comment by joshpalis** [comment]
> I see there is a good amount of failed tests in CI, was this occurring locally too?

No this does not occur locally, this is due to memory limitations of GH action runners. Issue https://github.com/opensearch-project/flow-framework/issues/377 details my current approach to mitigate this issue

**Comment by dbwiddis** [comment]
> I see there is a good amount of failed tests in CI, was this occurring locally too?

Tests were passing locally on my personal laptop where I submitted this.  Let me investigate.

**Comment by dbwiddis** [comment]
Failures are caused by not finding the json files:
> java.io.FileNotFoundException: Resource [mappings/global-context.json] not found in classpath

But they are present in `src/main/resources`

Screenshot 2024-01-08 at 9 20 59 AM

Possible classloader issue from the class loading the stream, will try to fix...

**Comment by dbwiddis** [comment]
Fixed. Was using relative classpath which worked with my other laptop config but apparently wasn't portable.

**Review by owaiskazi19 — APPROVED** [review]

**Review by amitgalitz — APPROVED** [review]

**Pull request merged**
