### PR TITLE
Fixing register agent tests

### PR DESCRIPTION
**Pull request by joshpalis**
### Description
Fixes register agent tests failing due to https://github.com/opensearch-project/ml-commons/pull/2204

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dbwiddis — APPROVED** [review]

**Review by amitgalitz — APPROVED** [review]

**Comment by joshpalis** [comment]
Seeing some failures in integration tests
```
» ERROR][o.o.m.e.i.MLIndicesHandler] [integTest-0] Failed to create index .plugins-ml-model
»  com.fasterxml.jackson.core.JsonParseException: Unexpected character ('}' (code 125)): was expecting double-quote to start field name
»   at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 54, column: 1]
»  	at com.fasterxml.jackson.core.JsonParser._constructReadException(JsonParser.java:2643) ~[jackson-core-2.17.0.jar:2.17.0]
»  	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:685) ~[jackson-core-2.17.0.jar:2.17.0]
»  	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddName(ReaderBasedJsonParser.java:1910) ~[jackson-core-2.17.0.jar:2.17.0]
»  	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:709) ~[jackson-core-2.17.0.jar:2.17.0]
»  	at org.opensearch.common.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:66) ~[opensearch-x-content-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
```

**Comment by dbwiddis** [comment]
> Unexpected character ('}' (code 125)): was expecting double-quote to start field name

Are we missing a mandatory field when creating the model?  CC: @dhrubo-os

**Comment by dbwiddis** [comment]
These errors are occurring on ML-Commons 2.x branch tests: see https://github.com/opensearch-project/ml-commons/actions/runs/8340647023/job/22825002139 for example.

Test run history for 2.x branch: https://github.com/opensearch-project/ml-commons/actions/workflows/CI-workflow.yml?query=branch%3A2.x

CC: @rbhavna @dhrubo-os

**Review by jackiehanyang — APPROVED** [review]

**Comment by dhrubo-os** [comment]
> > Unexpected character ('}' (code 125)): was expecting double-quote to start field name
> 
> Are we missing a mandatory field when creating the model? CC: @dhrubo-os
 
We fixed the bug now: https://github.com/opensearch-project/ml-commons/pull/2234

**Pull request merged**
