### PR TITLE
Removes unnecessary gradle properties

### PR DESCRIPTION
**Pull request by joshpalis**
### Description
Gradle properties seem to be directly pulled from OpenSearch gradle properties, this PR removes them as they are not necessary for this plugin. For example, `systemProp.org.gradle.warning.mode=fail` would fail a build outright when gradle APIs marked for future deprecation are used. This makes sense to set in OpenSearch to force a gradle version upgrade, but in this plugin's case, gradle version is only updated once OpenSearch does. 

Testing locally, the build and integration test pass with these properties removed.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dbwiddis — APPROVED** [review]
I wasted many hours figuring out that my BWCs were failing on this dang switch.

**Comment by amitgalitz** [comment]
I think this is used `options.forkOptions.memoryMaximumSize=2g` for the integTest cluster to determine heap size, not sure how it gets default otherwise

**Comment by dbwiddis** [comment]
> I think this is used `options.forkOptions.memoryMaximumSize=2g` for the integTest cluster to determine heap size, not sure how it gets default otherwise

Default if not specified is 1g.

Tests seem to be passing with this removed, though.

**Comment by amitgalitz** [comment]
> > I think this is used `options.forkOptions.memoryMaximumSize=2g` for the integTest cluster to determine heap size, not sure how it gets default otherwise
> 
> Default if not specified is 512mb.
> 
> Tests seem to be passing with this removed, though.

sounds good, just checked also that :run also works

**Review by amitgalitz — APPROVED** [review]

**Review by owaiskazi19 — APPROVED** [review]

**Pull request merged**
