### PR TITLE
Add user mapping to Workflow State index

### LINKED ISSUE #700: [BUG] The Workflow State mapping doesn't include the user field
### What is the bug?

The [Workflow State index mapping](https://github.com/opensearch-project/flow-framework/blob/main/src/main/resources/mappings/workflow-state.json) does not include a `user` field, just `user_outputs`.

### How can one reproduce the bug?

Attempt to query the existence of the "user" field using any of the clients, e.g., with the Go client:
```go
userExistsQuery := NewNestedQuery("user", NewExistsQuery("user.name"))
```
Result:
```
Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]
```

### What is the expected behavior?

Index mapping matches Java object XContent mapping.

### Do you have any additional context?

This is not user-facing but is relevant to queries that an admin may make.

### PR DESCRIPTION
**Pull request by dbwiddis**
### Description

Adds the missing mapping for the `user` field.  (Copy/paste from same field in the template mapping.)

### Issues Resolved

Fixes #700 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by amitgalitz** [comment]
So for this case the bwc could be a little different. Since we are only changing the mapping here I think where this would have an effect is in some sort of rollover, where we are creating the index again based of the new mapping. Would that be the only case here also in your opinion?

**Comment by dbwiddis** [comment]
> So for this case the bwc could be a little different. Since we are only changing the mapping here

I don't think we're changing the mapping. The `source` stored in the index will be identical. We're just documenting the mapping in the index metadata to permit clients to directly act on the source fields rather than having to parse it first.

> I think where this would have an effect is in some sort of rollover

This is a system index, so we're not rolling it over.  The concern here would be an index that already exists with the previous mapping; we would update the mapping with the new one which our code does if the versions differ (which reminds me, I should have incremented the mapping version, so that's a needed change here).

> Would that be the only case here also in your opinion?

The only case I see this being relevant is an upgrade from 2.12-2.14 to 2.15 or later, when the index metadata would be updated.

**Review by amitgalitz — APPROVED** [review]
LGTM, lets add a TODO or issue to have bwc with security enabled added and general increase of coverage with security

**Comment by dbwiddis** [comment]
> LGTM, lets add a TODO or issue to have bwc with security enabled added and general increase of coverage with security

https://github.com/opensearch-project/flow-framework/issues/710

**Review by minalsha — APPROVED** [review]

**Pull request merged**
