### PR TITLE
add sample templates for text to visualziation

### PR DESCRIPTION
**Pull request by ruanyl**
### Description
Add sample templates for text to visualization.
These templates will be used by OpenSearch-Dashboards plugin [dashboards-assistant](https://github.com/opensearch-project/dashboards-assistant) to setup text to visualization feature. Documentation could be found here: https://opensearch.org/docs/latest/dashboards/dashboards-assistant/text-to-visualization/

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/flow-framework/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ruanyl** [comment]
@dbwiddis @owaiskazi19 Could  you take a look the PR please?

**Comment by dbwiddis** [comment]
@ruanyl Will do. I saw it earlier but it was in draft until just no.

Note the spotless check is failing (looks like trailing whitespace).  Please run `./gradlew spotlessApply` and commit the difference.   Also add a section to the 2.x documentation on the change log.

**Review by dbwiddis — APPROVED** [review]
LGTM pending spotless fix

**Comment by owaiskazi19** [comment]
@ruanyl can you also some description about the use case for this template in the PR?

**Review by owaiskazi19 — APPROVED** [review]

**Comment by yuye-aws** [comment]
@ruanyl Is there going to be another PR on `t2vega_instruction_based_agent`?

**Comment by yuye-aws** [comment]
@ruanyl Is there going to be a PR adding `t2vega_agent` (without instruction)?

**Comment by dbwiddis** [comment]
Probably a changelog conflict with #968. Will wait until that's merged and toggle the backport label

**Pull request merged**
